import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "./components/navigationBar";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Faisal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={(inter.className, "dark:bg-green-600/30")}>
        <div className="fixed z-10 w-full pt-7">
          <NavigationBar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
